### ISSUE TITLE
Support CMake

### ISSUE THREAD

**Issue by flyfish101** [trailofbits/blight#43449]
Can we support cmake and compile_command.json ?  so that [MATE](https://github.com/GaloisInc/MATE) and other analyzer are able to use it for analyzing cmake projects.

**Comment by flyfish101** [comment]
Maybe it is like the the scan-build and analyze-build of clang static analyzer.

**Comment by woodruffw** [comment]
Could you say more about what you're expecting here? CMake is a "build generation" system, so blight shouldn't support it directly -- instead, a CMake build should be configured to use blight's build tool wrappers.

Support for `compile_commands.json` is tracked under #43447. All of the machinery for that is already present; someone just needs to tie it together.

**Comment by flyfish101** [comment]
Thanks for your reply.  I got it.
